version: "3"
services:
  node:
    build: ./node
    ports:
      - "3000:3000"
    volumes:
      - ../my-app:/home/node
      - ../my-app/node_modules:/app/node_modules
    command: "bash -c 'npm install && npm run dev'"
    working_dir: /home/node
    init: true
    tty: true
